import { Schema, Types, model } from "mongoose";
const productSchema = new Schema({
    name:{
        type:String,
        required:true,
        unique:true,
    },
    slug:{
        type:String,
        required:true,
    },
    description:{
        type:String,
        required:true,
    },
    image:{
        type:Object,
        required:true,
    },
    price:{
        type:Number,
        required:true,
    },
    discount:{
        type:Number,
        default:0,
    },
    finalPrice:{
        type:Number,
        required:true,
    },
    numberOfSellers:{
        type:Number,
        default:0,
    },
    status:{
        type:String,
        enum:['Active','Inactive'],
        default:'Active',
    },
    categoryId:{
        type:Types.ObjectId,
        ref:"Category",
        required:true,
    },
    restaurentId:{
        type:Types.ObjectId,
        ref:"Restaurent",
        required:true,
    },
    createdBy:{
        type: Types.ObjectId,
        ref:'User',
        required:true,
    },
    updatedBy:{
        type: Types.ObjectId,
        ref:'User',
        required:true,
    },
},{
    timestamps:true,
    toJSON:{virtuals:true},
    toObject:{virtuals:true},
});
productSchema.virtual("reviews",{
    ref:'Review',
    localField:'_id',
    foreignField:'productId'
});
const productModel = model('Product',productSchema);
export default productModel;